### ISSUE TITLE
How to build and run in development

### ISSUE THREAD

**Issue by categulario** [edfloreshz/do#3]
I realized that the readme lacks instructions on how to compile/run the application from the repo. I tried simply running `cargo run` but the app failed at runtime with some file not found error.

The second time I tried `cargo run` it failed with:

`Error: Failed with: no such table: __diesel_schema_migrations`

**Comment by edfloreshz** [comment]
This has to do with the migrations, I'm working to fix this.

**Comment by edfloreshz** [comment]
Fixed in latest [commit](https://github.com/edfloreshz/do/commit/0b88dde3eeda0389ee9cec2e828e5d44d20e31fc).
